### ISSUE TITLE
ssb-server extras problem

### ISSUE THREAD

**Issue by dpriskorn** [ssbc/patchfoo#10]
Hi. I read this:

> Install extras
> 
> To most effectively render things, patchfoo needs the ssb-backlinks
> and ssb-private ssb-server plugins. The ssb-search plugin is also helpful, for fulltext search of your SSB DB.
> 
> If you are using a ssb-server distribution like Patchwork, Patchbay or Oasis's ssb-server, these plugins are already included. If you are using ssb-server from the command-line, the plugins have to be installed separately:
> 
> sbot plugins.install ssb-backlinks
> sbot plugins.install ssb-private
> sbot plugins.install ssb-search

I succesfully installed ssb-server and succeded in installing git-ssb and it seems to work fine :)
I get errors like this on with sbot though:
`$ sbot plugins.install ssb-backlinks

/usr/lib/node_modules/ssb-server/node_modules/muxrpcli/index.js:123
      throw err
      ^
{
  message: "Cannot set property 'module' of undefined",
  name: 'TypeError',
  stack: "TypeError: Cannot set property 'module' of undefined\n" +
    '    at Object.install (/usr/lib/node_modules/ssb-server/node_modules/ssb-plugins/index.js:116:23)\n' +
    '    at Object.hooked (/usr/lib/node_modules/ssb-server/node_modules/hoox/index.js:10:15)\n' +
    '    at Object.localCall (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:31:29)\n' +
    '    at Object.<anonymous> (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/local-api.js:37:22)\n' +
    '    at PacketStreamSubstream.stream.read (/usr/lib/node_modules/ssb-server/node_modules/muxrpc/stream.js:69:23)\n' +
    '    at PacketStream._onstream (/usr/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:228:11)\n' +
    '    at PacketStream.write (/usr/lib/node_modules/ssb-server/node_modules/packet-stream/index.js:135:41)\n' +
    '    at /usr/lib/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15\n' +
    '    at /usr/lib/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:24:37\n' +
    '    at /usr/lib/node_modules/ssb-server/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11'
}
`

Any ideas?

**Comment by clehner** [comment]
I think you can work around this error by adding a dummy argument after the plugin name (re: %lvLBrXSGAulTwaFSUBKCgttC0/mO2BAnXvLOCnI+KsY=.sha256). Like this:

sbot plugins.install ssb-backlinks --yes

Also, this repo is deprecated. A better place for issues would be on the repo on git-ssb: %YAg1hicat+2GELjE2QJzDwlAWcx0ML+1sXEdsWwvdt8=.sha256

**Comment by dpriskorn** [comment]
Thanks, I'm trying to install patchfoo, but I'm not successful it seems. I don't have a working ssb client yet so I hoped to get help here instead.

**Comment by clehner** [comment]
Hi Egil,
I read you had installed git-ssb. Have you tried using git-ssb-web? It is a web UI included in git-ssb, and has functionality to open issues on repos.
Regards,
Charles/cel

**Comment by dpriskorn** [comment]
Will try that next. 😀
