### ISSUE TITLE
corrupt dependencies, install hanging

### ISSUE THREAD

**Issue by cyisfor** [ssbc/patchfoo#5]
```
npm http fetch GET 200 http://localhost:8043/sodium-chloride 119ms
npm verb stack Error: sha256-HEaenlmoqs5++b9QaY2EKGnsD2wLpA4/9hqExgaT7TI= integrity checksum failed when using sha256: wanted sha256-HEaenlmoqs5++b9QaY2EKGnsD2wLpA4/9hqExgaT7TI= but got sha512-E39SpyZlSOYTlIBsyEnvkasenJck0VD6YVYPOQAKmc8ZxZZlPve1y3nZuSAujWYJWssQbmpf2I19DQ/eGeMqAg== sha256-OgxOBn+YXb8FfcWORZxjoJRA0ltd4zC3RvVzNp/MdWg=. (2825 bytes)
```
Then `npm install --registry=http://localhost:8043` hangs forever. 

Installed both "npm-registry" plugin and "npm-backlinks." Running sbot server.

node v8.1.1 npm v6.0.1

**Comment by cyisfor** [comment]
Incidentally what's stalling is sodium-native, as in:
```
curl http://localhost:8043/sodium-native
```
produces no result, and just sits there until the socket times out. I can install sodium-native just fine with the default registry, but it still checks sodium-native on the :8043 registry, and hangs.

**Comment by cyisfor** [comment]
the git-ssb web page on [ssb-npm-101](http://localhost:7718%25eSY9ewHDPzCJhl%2Bu9hivtWvvjJbSg%2BVmaxyqmvfEfK4%3D.sha256) seems to indicate that sodium-native is too big to squeeze through scuttlebutt by default, so I tried running `sbot server --blobs.max 10000000` but it's still hanging, as far as I can tell. At least... it's been long enough to download 10 megabytes, and there sure isn't any progress indicator, or any indication of what blobs ssb-npm-registry is getting. I'll leave it hanging I guess, see if it succeeds or times out again.

**Comment by cyisfor** [comment]
Okay, it took a while, but I did eventually get sodium-native, and patchfoo seems to be running. I'll leave this open until someone mentions the `--blobs.max 1000000` thing in the README here. But I think that might be the solution. I also couldn't replicate that "verb stack error" so it might not even be related.

**Comment by kode54** [comment]
Still getting this error after increasing my blobs max, using a config string, to 10'000'000 (ticks added for clarity), and wiping out my existing blobs directory.

```
"blobs": { "max": 10000000 }
```
